import Vue from 'vue'
import { Button, Container, Header, Aside, Main, Footer, Menu, MenuItem, Submenu, Icon, Input, Carousel, CarouselItem, Table, TableColumn, Image, Backtop, Form, FormItem, Checkbox, Select, Option, Col, TimePicker, Switch, Radio, CheckboxGroup, RadioGroup, DatePicker, Message, MessageBox, Steps, Step, Loading, Upload, Link, Dialog, Tag, InputNumber, Pagination, Collapse, CollapseItem } from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Icon)
Vue.use(Input)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Image)
Vue.use(Backtop)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Checkbox)
Vue.use(Select)
Vue.use(Option)
Vue.use(Col)
Vue.use(TimePicker)
Vue.use(Switch)
Vue.use(Radio)
Vue.use(CheckboxGroup)
Vue.use(RadioGroup)
Vue.use(DatePicker)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
Vue.use(Steps)
Vue.use(Step)
Vue.prototype.$loading = Loading
Vue.use(Upload)
Vue.use(Link)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(InputNumber)
Vue.use(Pagination)
Vue.use(Collapse)
Vue.use(CollapseItem)
